# code: language=ansible
- name: Install packages
  apt:
    name:
      - shadowsocks-libev
    update_cache: true
- name: Copy /etc/shadowsocks-libev/config.json
  template:
    src: config.json.j2
    dest: /etc/shadowsocks-libev/config.json
    mode: 0644
  notify:
    - Restart shadowsocks-libev
- name: Enable shadowsocks-libev
  service:
    name: shadowsocks-libev
    state: started
    enabled: true
